### ISSUE TITLE
:bug: [BUG]: CERTIFICATE_VERIFY_FAILED error with canarie-api monitoring

### ISSUE THREAD

**Issue by tlvu** [bird-house/birdhouse-deploy#198]
## Summary

Using LetsEncrypt SSL certificate, the canarie-api monitoring page https://lvupavicsdev.ouranos.ca/canarie/node/service/status fail with a bunch of `CERTIFICATE_VERIFY_FAILED` but all the services are working properly.

This is most likely due to https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ meaning the openssl library in the proxy container is too old.

This bug only impact PAVICS deployment using LetsEncrypt certificate and only if the canarie-api monitoring matter.  Otherwise all other services are still working fine (Jenkins run all pass http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/1253/console).

Ouranos production has been switched to use another SSL certificate provider as a work-around.

@moulab88 FYI

## Details

![Screenshot 2021-09-30 at 14-55-31 Ouranos - Node Service](https://user-images.githubusercontent.com/11966697/135514387-9018c976-9484-4add-abb4-fa8617d09929.png)

## How to reproduce

```
$ docker exec proxy python -c "import requests; requests.request('GET', 'https://lvupavicsmaster.ouranos.ca/geoserver'
> )"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
```

**Comment by tlvu** [comment]
Root cause is the `request` python library bundle their own CA root certificates bundle which is less up-to-date than the one the OS provide !  This is really annoying.

```
$ docker exec proxy python -c "import requests; print requests.certs.where()"
/usr/local/lib/python2.7/dist-packages/requests/cacert.pem

$ docker exec -it proxy bash
root@37ed3a2a03ae:/opt/local/src/CanarieAPI/canarieapi# REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt python -c "import requests; requests.request('GET', 'https://lvupavicsmaster.ouranos.ca/geoserver')"
root@37ed3a2a03ae:/opt/local/src/CanarieAPI/canarieapi#

# No error "requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)"
```
